### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by Hildepont** [jbaiter/gphoto2-cffi#15]
Hello, on debian 8.6 (AMD64), I try to install all the dependencies for Spreads (thus gphoto2 with python 2.7). When I write 
`$ pip install git+https://github.com/jbaiter/gphoto2-cffi.git`, I got an error : 

```
Downloading/unpacking git+https://github.com/jbaiter/gphoto2-cffi.git
  Cloning https://github.com/jbaiter/gphoto2-cffi.git to /tmp/pip-NUopFt-build
  Running setup.py (path:/tmp/pip-NUopFt-build/setup.py) egg_info for package from git+https://github.com/jbaiter/gphoto2-cffi.git

    Installed /tmp/pip-NUopFt-build/cffi-1.8.3-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-NUopFt-build/setup.py", line 47, in <module>
        zip_safe=False,
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
    ImportError: No module named setuptools_ext
    Complete output from command python setup.py egg_info:


Installed /tmp/pip-NUopFt-build/cffi-1.8.3-py2.7-linux-x86_64.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-NUopFt-build/setup.py", line 47, in <module>

    zip_safe=False,

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options

    ep.load()(self, ep.name, value)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load

    ['__name__'])

ImportError: No module named setuptools_ext

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-NUopFt-build
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by Hildepont** [comment]
Seems to come from cffi like [here](https://github.com/byt3bl33d3r/MITMf/issues/163). I remove and reinstall cffi : 
`apt-get remove python-cffi`
`pip install cffi==1.7.0`
now it works…
