### ISSUE TITLE
v0.4 on pip is broken

### ISSUE THREAD

**Issue by define-private-public** [jbaiter/gphoto2-cffi#23]
I tried doing the `--upgrade` command via pip and this was spat out at me:

```
Collecting gphoto2-cffi
  Downloading gphoto2-cffi-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8tco5zsf/gphoto2-cffi/setup.py", line 47, in <module>
        zip_safe=False,
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 188, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "gphoto2cffi/backend_build.py", line 5, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'gphoto2.cdef')) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'gphoto2cffi/gphoto2.cdef'
```

I Checked the 0.4 package on PyPi, and it looks like you forgot to put `gphoto2.cdef` in there.

**Comment by jbaiter** [comment]
Looks like something changed in setuptools that made the `package_data` keyword being ignored. I now added a `MANIFEST.in` and released a new v0.4.1 version.
