### ISSUE TITLE
cannot import gphoto2cffi as gp using python 3

### ISSUE THREAD

**Issue by knob-creek** [jbaiter/gphoto2-cffi#30]
This is reproducible on Debian (raspberry pi) as well as on Ubuntu:
when trying to import gphoto2cffi i get the subsequent error.  I am not a python developer so i am totally stuck here.  (Either nobody uses this lib with python 3 or i am missing something very basic here.)

>>> import gphoto2cffi as gp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gphoto2cffi/__init__.py", line 1, in <module>
    from .gphoto2 import (Camera, list_cameras, supported_cameras,
  File "/usr/lib/python3/dist-packages/gphoto2cffi/gphoto2.py", line 15, in <module>
    from . import errors, backend
  File "/usr/lib/python3/dist-packages/gphoto2cffi/backend.py", line 56, in <module>
    'extract_exif': _lib.GP_FILE_OPERATION_EXIF})
  File "/usr/lib/python3.5/enum.py", line 243, in __call__
    return cls._create_(value, names, module=module, qualname=qualname, type=type, start=start)
  File "/usr/lib/python3.5/enum.py", line 343, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)
  File "/usr/lib/python3.5/enum.py", line 114, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict)
TypeError: type() argument 1 must be str, not bytes

**Comment by knob-creek** [comment]
I just saw: this is a duplicate of #7.
Both OSs come with 0.3-a1.
